import { PublicKey } from "@solana/web3.js";

export const SOLEND_PROGRAM_ID = new PublicKey(
  "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo"
);

export const MARKET_AUTHORITY = new PublicKey(
  "GDmSxpPzLkfxxr6dHLNRnCoYVGzvgc41tozkrr4pHTjB"
);

export const MARKET_OWNER = new PublicKey(
  "5pHk2TmnqQzRF9L6egy5FfiyBgS7G9cMZ5RFaJAvghzw"
);

export const SLND_PRICE_ORACLE = new PublicKey(
  "7QKyBR3zLRhoEH5UMjcG8emDD2J2CCDmkxv3qsa2Mqif"
);

export const MARKET_PDA_MAIN_POOL = new PublicKey(
  "DdZR6zRFiUt4S5mg7AV1uKB2z1f1WzcNYCaTEEWPAuby"
);

// Lending Market ID
export const SOLEND_LENDING_MARKET_ID_MAIN_POOL = new PublicKey(
  "4UpD2fh7xH3VP9QQaXtsS1YY3bxzWhtfpks7FatyKvdY"
);

export const SOLEND_LENDING_MARKET_ID_TURBO_SOL_POOL = new PublicKey(
  "7RCz8wb6WXxUhAigok9ttgrVgDFFFbibcirECzWSBauM"
);

export const SOLEND_LENDING_MARKET_ID_USDH_POOL = new PublicKey(
  "Epa6Sy5rhxCxEdmYu6iKKoFjJamJUJw8myjxuhfX2YJi"
);

export const SOLEND_LENDING_MARKET_ID_STEPN_POOL = new PublicKey(
  "BjsAGLZzAgBUsiaTTDQv7PWDUDL9dQfKvYwb4q6FoDuD"
);

export const SOLEND_LENDING_MARKET_ID_STABLE_POOL = new PublicKey(
  "GktVYgkstojYd8nVXGXKJHi7SstvgZ6pkQqQhUPD7y7Q"
);

export const SOLEND_LENDING_MARKET_ID_BASIS_POOL = new PublicKey(
  "93fqxupYFmvXWWB9ptSp5pyAV9b7kgUpooqc5hWtaXYz"
);

export const SOLEND_LENDING_MARKET_ID_STEP_POOL = new PublicKey(
  "DxdnNmdWHcW6RGTYiD5ms5f7LNZBaA7Kd1nMfASnzwdY"
);

export const SOLEND_LENDING_MARKET_ID_AURORY_POOL = new PublicKey(
  "7Sy8M8cXZFyyyHRDyiLi1WumPcgpnYUviuPm1Dp3XFmb"
);

export const SOLEND_LENDING_MARKET_ID_LENDING_POOL = new PublicKey(
  "C3VQi4sKNXVsG36zhUnvNasXPhzGmWWVpaeSPv5Tf2AB"
);

export const SOLEND_LENDING_MARKET_ID_SHADOW_POOL = new PublicKey(
  "Foo9vqN6fj1NyymHmD1gwZkgVgEqzNSrwyeqyoLYGe7j"
);

export const SOLEND_LENDING_MARKET_ID_NFT_POOL = new PublicKey(
  "29yTiqjGdoNiRLMVc7ZoqFpbW3gkmefwMG9SUiMMD4J9"
);

export const SOLEND_LENDING_MARKET_ID_UXD_POOL = new PublicKey(
  "HCuEqcXaGeioiJf5vNMTyQC7HMPqJm5aZPkSjA2qceDS"
);

export const SOLEND_LENDING_MARKET_ID_COIN98_POOL = new PublicKey(
  "7tiNvRHSjYDfc6usrWnSNPyuN68xQfKs1ZG2oqtR5F46"
);

export const SOLEND_LENDING_MARKET_ID_DOG_POOL = new PublicKey(
  "HASr6hiYVoRcVXk3GttC4PjBBPQ3sGYDzE7HSPJdcke6"
);

export const SOLEND_LENDING_MARKET_ID_STAR_ATLAS_POOL = new PublicKey(
  "99S4iReDsyxKDViKdXQKWDcB6C3waDmfPWWyb5HAbcZF"
);

export const SOLEND_LENDING_MARKET_ID_BONFIDA_POOL = new PublicKey(
  "91taAt3bocVZwcChVgZTTaQYt2WpBVE3M9PkWekFQx4J"
);

export const SOLEND_LENDING_MARKET_ID_INVICTUS_POOL = new PublicKey(
  "5i8SzwX2LjpGUxLZRJ8EiYohpuKgW2FYDFhVjhGj66P1"
);

export const SOLEND_LENDING_MARKET_ID_ALL = [
  SOLEND_LENDING_MARKET_ID_MAIN_POOL,
  SOLEND_LENDING_MARKET_ID_TURBO_SOL_POOL,
  SOLEND_LENDING_MARKET_ID_USDH_POOL,
  SOLEND_LENDING_MARKET_ID_STEPN_POOL,
  SOLEND_LENDING_MARKET_ID_STABLE_POOL,
  SOLEND_LENDING_MARKET_ID_BASIS_POOL,
  SOLEND_LENDING_MARKET_ID_STEP_POOL,
  SOLEND_LENDING_MARKET_ID_AURORY_POOL,
  SOLEND_LENDING_MARKET_ID_LENDING_POOL,
  SOLEND_LENDING_MARKET_ID_SHADOW_POOL,
  SOLEND_LENDING_MARKET_ID_NFT_POOL,
  SOLEND_LENDING_MARKET_ID_UXD_POOL,
  SOLEND_LENDING_MARKET_ID_COIN98_POOL,
  SOLEND_LENDING_MARKET_ID_DOG_POOL,
  SOLEND_LENDING_MARKET_ID_STAR_ATLAS_POOL,
  SOLEND_LENDING_MARKET_ID_BONFIDA_POOL,
  SOLEND_LENDING_MARKET_ID_INVICTUS_POOL,
];
